$(call add-clean-step, rm -rf $(PRODUCT_OUT)/system/app/CalendarFossify)
$(call add-clean-step, rm -rf $(PRODUCT_OUT)/system/app/Iceraven)
$(call add-clean-step, rm -rf $(PRODUCT_OUT)/system/app/MotoCalculator)
$(call add-clean-step, rm -rf $(PRODUCT_OUT)/system/app/GalleryFossify)
$(call add-clean-step, rm -rf $(PRODUCT_OUT)/system/priv-app/stats)
$(call add-clean-step, rm -rf $(PRODUCT_OUT)/system/app/SimpleMusicPlayer)
$(call add-clean-step, rm -rf $(PRODUCT_OUT)/system/app/WeatherIcons)
